### PR TITLE
fix NOT_NULL migration test to avoid catching "DROP NOT NULL"

### PR DESCRIPTION
**Pull request by POD666**
https://github.com/3YOURMIND/django-migration-linter/issues/67

Should I also bump the version and add a note to the CHANGELOG.md or you will do it by yourself?

### CODE REVIEW

**Comment by POD666** [comment]
It might be helpful:
image
So "DROP NOT NULL" is not caught.

**Comment by POD666** [comment]
Hmm, the added testcase is failing for SQLite and MySql.
`python ../../manage.py sqlmigrate app_alter_column_drop_not_null 0002` outputs:
```
BEGIN;
--
-- Alter field not_null_field on a
--
ALTER TABLE "app_alter_column_drop_not_null_a" RENAME TO "app_alter_column_drop_not_null_a__old";
CREATE TABLE "app_alter_column_drop_not_null_a" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "not_null_field" integer NULL);
INSERT INTO "app_alter_column_drop_not_null_a" ("id", "not_null_field") SELECT "id", "not_null_field" FROM "app_alter_column_drop_not_null_a__old";
DROP TABLE "app_alter_column_drop_not_null_a__old";
COMMIT;
```
It contains "NOT NULL" for "id", but if this one fails how other tests work?

**Comment by POD666** [comment]
Well, I see
```
$ python ../../manage.py lintmigrations --no-cache
...
(app_alter_column_drop_not_null, 0001_create_table)... OK
(app_alter_column_drop_not_null, 0002_drop_not_null)... ERR
	RENAMING tables
```
It's caught as "RENAMING tables" which is true, because:
```
$ python ../../manage.py sqlmigrate app_alter_column_drop_not_null 0002
BEGIN;
--
-- Alter field not_null_field on A
--
ALTER TABLE "app_alter_column_drop_not_null_a" RENAME TO "app_alter_column_drop_not_null_a__old";
CREATE TABLE "app_alter_column_drop_not_null_a" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "not_null_field" integer NULL);
INSERT INTO "app_alter_column_drop_not_null_a" ("id", "not_null_field") SELECT "id", "not_null_field" FROM "app_alter_column_drop_not_null_a__old";
DROP TABLE "app_alter_column_drop_not_null_a__old";
COMMIT;
```

Any thoughts?

**Comment by POD666** [comment]
I'm a bit confused. Should `test_accept_not_null_column_followed_by_adding_default` also fail?
```
$ python ../../manage.py lintmigrations --no-cache
...
(app_add_not_null_column_followed_by_default, 0001_initial)... OK
(app_add_not_null_column_followed_by_default, 0002_a_not_null_field)... ERR
	RENAMING tables
...
```

**Comment by David-Wobrock** [comment]
Hi @POD666 , sorry for answering a bit late.
First of all, thanks for a lot for taking the time to contribute.

The 2 test cases seem to be failing because:
* for sqlite, we are indeed renaming the field

The SQL
```
> python manage.py sqlmigrate app_alter_column_drop_not_null 0002 --database sqlite
BEGIN;
--
-- Alter field not_null_field on a
--
ALTER TABLE "app_alter_column_drop_not_null_a" RENAME TO "app_alter_column_drop_not_null_a__old";
CREATE TABLE "app_alter_column_drop_not_null_a" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "not_null_field" integer NULL);
INSERT INTO "app_alter_column_drop_not_null_a" ("id", "not_null_field") SELECT "id", "not_null_field" FROM "app_alter_column_drop_not_null_a__old";
DROP TABLE "app_alter_column_drop_not_null_a__old";
COMMIT;
```
Thus 
```
(app_alter_column_drop_not_null, 0001_create_table)... OK
(app_alter_column_drop_not_null, 0002_drop_not_null)... ERR
        RENAMING tables
```
Which is backward compatible, so that would be a bug in the linter.

* Another bug is what is happening for the mysql test case:

SQL
```
> python manage.py sqlmigrate app_alter_column_drop_not_null 0002 --database mysql
BEGIN;
--
-- Alter field not_null_field on a
--
ALTER TABLE `app_alter_column_drop_not_null_a` MODIFY `not_null_field` integer NULL;
COMMIT;
```
and
```
(app_alter_column_drop_not_null, 0001_create_table)... OK
(app_alter_column_drop_not_null, 0002_drop_not_null)... ERR
        ALTERING columns (Could be backward compatible. You may ignore this migration.) (table: app_alter_column_drop_not_null_a)

**Pull request merged**
