### PR TITLE
Do not check if .git folder exists

### LINKED ISSUE #31: drop check of .git dir on django_path
There's no need to check for ``.git`` dir, git diff already fails if not inside a git repository
```
# git diff --name-only --diff-filter=A whatever
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

On a repo that the django project is not in the root, there's no $django_path/`.git` dir there and is a proper git repo

### PR DESCRIPTION
**Pull request by David-Wobrock**
git commands will fail anyway if not present

Fixes #31

### CODE REVIEW

**Comment by flixx** [comment]
Well, it works, but I'm not sure if it is an improvement since the error message is less explicit now :-/ :

   django-migration-linter tests/test_project_fixtures/test_django_without_git_project/ sadasd
Traceback (most recent call last):
  File "/home/felix/.local/share/virtualenvs/django-migration-linter-kfifiS1d/bin/django-migration-linter", line 11, in <module>

```
$ django-migration-linter tests/test_project_fixtures/test_django_without_git_project/ sadasd
load_entry_point('django-migration-linter==0.1.0', 'console_scripts', 'django-migration-linter')()
  File "/home/felix/.local/share/virtualenvs/django-migration-linter-kfifiS1d/lib/python3.6/site-packages/django_migration_linter-0.1.0-py3.6.egg/django_migration_linter/migration_linter.py", line 343, in _main
  File "/home/felix/.local/share/virtualenvs/django-migration-linter-kfifiS1d/lib/python3.6/site-packages/django_migration_linter-0.1.0-py3.6.egg/django_migration_linter/migration_linter.py", line 137, in lint_all_migrations
  File "/home/felix/.local/share/virtualenvs/django-migration-linter-kfifiS1d/lib/python3.6/site-packages/django_migration_linter-0.1.0-py3.6.egg/django_migration_linter/migration_linter.py", line 221, in _gather_migrations_git
Exception: Error while executing git diff command
```

Before it was:
```
ValueError: The given project tests/test_project_fixtures/test_django_without_git_project/ does not seem to be versioned by git.
```
which is easier to understand. 
However, I would be fine with merging it anyway. @David-Wobrock please decide and go ahead.

**Comment by flixx** [comment]
I changed a `logger.info()` to a `logger.error()` to show the error from git in the console. Now the error looks like this:

```
$ django-migration-linter tests/test_project_fixtures/test_django_without_git_project/ sadasd
Error while git diff command:
fatal: ambiguous argument 'sadasd': unknown revision or path not in the working tree.Use '--' to separate paths from revisions, like this:'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/home/felix/.local/share/virtualenvs/django-migration-linter-kfifiS1d/bin/django-migration-linter", line 11, in <module>
    load_entry_point('django-migration-linter==0.1.0', 'console_scripts', 'django-migration-linter')()
  File "/home/felix/.local/share/virtualenvs/django-migration-linter-kfifiS1d/lib/python3.6/site-packages/django_migration_linter-0.1.0-py3.6.egg/django_migration_linter/migration_linter.py", line 343, in _main
  File "/home/felix/.local/share/virtualenvs/django-migration-linter-kfifiS1d/lib/python3.6/site-packages/django_migration_linter-0.1.0-py3.6.egg/django_migration_linter/migration_linter.py", line 137, in lint_all_migrations
  File "/home/felix/.local/share/virtualenvs/django-migration-linter-kfifiS1d/lib/python3.6/site-packages/django_migration_linter-0.1.0-py3.6.egg/django_migration_linter/migration_linter.py", line 221, in _gather_migrations_git
Exception: Error while executing git diff command
```
which is okay, I guess.

**Comment by David-Wobrock** [comment]
Yeah, I don't know either if we want this change.
It doesn't cost us a lot to test if the `.git` folder exists, and it makes a possible error message clearer.

If you agree, we can close this PR and #31

**Comment by flixx** [comment]
Because this is not only a cosmetic change but fixes a real problem (I was unaware of that), I'll megre this on here. This closes #31 .

**Pull request merged**
