### PR TITLE
 make should_ignore_migration check for IgnoreMigration

### PR DESCRIPTION
**Pull request by tuky**

### CODE REVIEW

**Comment by tuky** [comment]
this by the way should fix the overall usability for projects which completely delete models after migrations that altered the deleted model. for those `sqlmigrate` fails with a

```
django.db.utils.ProgrammingError: (1146, "Table '...' doesn't exist")
```

and now you can easily ignore such migrations.

**Comment by tuky** [comment]
Thanks for the review. All valid points, I hope I fulfilled the to your satisfaction.

**Comment by flixx** [comment]
@tuky Almost there :) Please also remove `IGNORE_MIGRATION_SQL` in `operations.py` since it is unnecessary now.
I just tested with our big codebase and things seem to be fine.
So if you remove that constant, you've got my approval :)

**Comment by tuky** [comment]
Of course, thx and done.

**Pull request merged**
