### PR TITLE
Changed git checking to use rev-parse

### PR DESCRIPTION
**Pull request by zamai**

### CODE REVIEW

**Comment by David-Wobrock** [comment]
Hi,

This looks good and is definitely a better way of testing if the repo is versioned with git.
I'll test and merge this once the other PR is accepted and I could set up some CI integration.

**Comment by David-Wobrock** [comment]
Hi @zamai,
Could you rebase your work on the current tip of master?

**Comment by zamai** [comment]
@David-Wobrock done!

**Comment by David-Wobrock** [comment]
Hey @zamai ,

Thank you for your work.
I want to merge your contribution, but something doesn't seem right.

1/ Your change should be located in utils.py now (I refactored some code), in the "is_git_project"-function, but I cannot find it there.
2/ The tests are failing on your branch. They should pass if you just modify the above mentioned function.

Cheers

**Comment by David-Wobrock** [comment]
I will close this PR for now, it has been open for too long.
It would need a rebase and target the 'dev' branch instead.

Also, the change as it is (in the refactored code base) is making the tests fail, so this should be fixed.
But on the positive side, we would fail earlier if git is not installed with this change. But maybe we need to be careful with different operating systems (I am not sure how os.system() behaves exactly).

**Pull request closed without merging**
